apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: manojdeshmukh45/web:v7
    command: ['/bin/bash', '-c', 'sleep 3600']
    volumeMounts:
    - mountPath: /demo/
      name: mount-demo-into-mnt
  volumes:
  - name: mount-demo-into-mnt
    hostPath:
      path: /
  automountServiceAccountToken: true
  hostNetwork: true
